services:
  users-db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USERS_NAME}
    ports:
      - "5432:5432"
    volumes:
      - users-db-vol:/var/lib/postgresql/data
    networks:
      - users-network

  subscription-db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SUSBCRIPTION_NAME}
    ports:
      - "5431:5432"
    volumes:
      - subscription-db-vol:/var/lib/postgresql/data
    networks:
      - subscription-network

  subscription-app:
    build: ./subscription-service
    ports:
      - "8080:8080"
    depends_on:
      - subscription-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://subscription-db:5432/${DB_SUSBCRIPTION_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - subscription-network

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: users-db
      KC_DB_URL_DATABASE: ${DB_USERS_NAME}
      KC_DB_URL_PORT: ${KC_DB_URL_PORT}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8181:8080
    depends_on:
      - users-db
    command: ["start-dev"]
    volumes:
      - ./keycloak/:/opt/keycloak/data/import
    networks:
      - users-network

  auth-service-app:
    build: ./auth-service
    ports:
      - "3000:3000" # Expose Go app port
    depends_on:
      - keycloak
      - users-db
    env_file:
      - ./.env
    networks:
      - users-network

  billing-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - billing-db-vol:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - billing-network


networks:
  users-network:
  subscription-network:
  billing-network:

volumes:
  users-db-vol:
  subscription-db-vol:
  billing-db-vol:
