services:
  subscription-db:
    image: postgres
    environment:
      POSTGRES_USER: achraf
      POSTGRES_PASSWORD: 4182
      POSTGRES_DB: subscriptions_db
    ports:
      - "5431:5432"
    volumes:
      - subscription-db-vol:/var/lib/postgresql/data
    networks:
      - subscription-network

networks:
  subscription-network:

volumes:
  subscription-db-vol:
