apiVersion: apps/v1
kind: Deployment
metadata:
  name:  auth-service
  namespace: auth-service
  labels:
    app:  auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  auth-service
    spec:
      containers:
      - name:  auth-service
        image:  workeo/auth-service:0.1
        env:
        - name: KEYCLOAK_URL
          value: keycloak:8086
        - name: KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_CLIENT_SECRET
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: SERVER_URL
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: SERVER_URL
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 600m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /_status/heatlhz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/ready
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  3000
          name:  auth-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080        
      targetPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service
spec:
  type: ExternalName
  externalName: auth-service.auth-service.svc.cluster.local  # Fully qualified name

