apiVersion: apps/v1
kind: Deployment
metadata:
  name:  auth-service
  namespace: auth-service
  labels:
    app:  auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  auth-service
    spec:
      containers:
      - name:  auth-service
        image:  workeo/auth-service:0.1
        env:
        - name: KEYCLOAK_URL
          value: keycloak:8086
        - name: KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_CLIENT_SECRET
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: SERVER_URL
          valueFrom:
            secretKeyRef:
              name: auth-go-secrets
              key: SERVER_URL
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort:  3000
          name:  auth-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080        
      targetPort: 3000


