apiVersion: apps/v1
kind: Deployment
metadata:
  name:  billing-service
  namespace: billing-service
  labels:
    app:  billing-service
spec:
  selector:
    matchLabels:
      app: billing-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  billing-service
    spec:
      containers:
      - name:  billing-service
        image:  workeo/billing-service:0.1
        env:
        - name: MONGO_COLLECTION
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: MONGO_COLLECTION
        - name: MONGO_HOST
          value: billing-db
        - name: MONGO_PORT
          value: "8085"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: MONGO_PASSWORD
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: billing-secrets
              key: DJANGO_SECRET_KEY
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort:  8000
          name:  billing-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  selector:
    app: billing-service
  ports:
    - protocol: TCP
      port: 8082        
      targetPort: 8000
