apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth-service
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak
        command:
          - "/opt/keycloak/bin/kc.sh"  # or the appropriate startup script
          - "start-dev" 
        env:
        - name: KC_DB
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KC_DB
        - name: KC_DB_URL_HOST
          value: auth-db
        - name: KC_DB_URL_DATABASE
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: DB_USERS_NAME
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KC_DB_USERNAME
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KC_DB_PASSWORD
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-config-volume
          mountPath: /opt/keycloak/data/import
          subPath: import
      volumes:
      - name: keycloak-config-volume
        configMap:
          name: keycloak-config
        
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: auth-service
  labels:
    app: keycloak
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8080
  selector:
    app: keycloak
