apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak
        env:
        - name: KC_DB
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KC_DB
        - name: KC_DB_URL_HOST
          value: auth-db
        - name: KC_DB_URL_DATABASE
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KC_DB_URL_DATABASE
        - name: KC_DB_URL_PORT
          value: "8085"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KC_DB_USERNAME
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KC_DB_PASSWORD
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-kc-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /_status/heatlhz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/ready
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-config-volume
          mountPath: /opt/jboss/keycloak/standalone/data/import.json
          subPath: import.json
      volumes:
      - name: keycloak-config-volume
        hostPath:                  
          path: /home/achraf/Documents/Let-s-Work/keycloak/keycloak
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: auth-service
  labels:
    app: keycloak
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8080
  selector:
    app: keycloak
