apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: workeo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:15.0.2
        env:
        - name: DB_VENDOR
          value: POSTGRES
        - name: DB_ADDR
          value: auth-postgresql.databases.svc.cluster.local
        - name: DB_DATABASE
          value: keycloakdb
        - name: DB_USER
          value: keycloakuser
        - name: DB_PASSWORD
          value: password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /_status/heatlhz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/ready
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-config-volume
          mountPath: /opt/jboss/keycloak/standalone/data/import.json
          subPath: import.json
      volumes:
      - name: keycloak-config-volume
        hostPath:                  
          path: /home/achraf/Documents/Let-s-Work/keycloak/keycloak
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
