apiVersion: apps/v1
kind: Deployment
metadata:
  name:  subscription-service
  namespace: subscription-service
  labels:
    app:  subscription-service
spec:
  selector:
    matchLabels:
      app: subscription-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  subscription-service
    spec:
      containers:
      - name:  subscription-service
        image:  workeo/subscription-service:0.1
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: subscription-secrets
              key: DB_PASSWORD
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: subscription-secrets
              key: DB_USER
        - name: DB_HOST
          value: 10.244.2.12:8085
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort:  8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  namespace: subscription-service
  labels:
    app: subscription-service
spec:
  selector:
    app: subscription-service
  ports:
    - protocol: TCP
      port: 8081        
      targetPort: 8080
